[package]
name = "rocket"
version = "0.1.0"
edition = "2018"

[dependencies]
tui = { version = "0.16.0", default-features = false, features = ["crossterm"] }
crossterm = "0.21.0"
unicode-segmentation = "1.8.0"
regex = "1.5.4"
lazy_static = "1.4.0"
